Tagging System 2
CS2103AUG2016-W10-C4/main pull request #158
Opened 2016-10-30 10:48 UTC by xdrawks

Completed:
Adding tags via the add command
Delete tags from a task
Delete tags globally
Rename a tag
Show global list of tags without GUI
Validation checks for all the above commands

Not completed:
Entire test suite for Tagging system

2016-10-31 13:35 UTC, li-kai requested changes
Just some changes, but mostly looks acceptable to me.

2016-10-31 13:35 UTC, li-kai commented on src/main/java/seedu/todo/logic/commands/TagCommand.java
> +            = "An existing tag name, and a new tag name is required.";
Phrasing is a little weird. "Please provide an existing tag and a new name for it." or something. Same with the next one.

2016-10-31 13:35 UTC, li-kai commented on src/main/java/seedu/todo/model/tag/UniqueTagCollectionValidator.java
> +    private void validateTagNamesDoNotExist(Collection<Tag> tagPool, String... tagNames) {
```
Set<String> tagNamesSet = Sets.newHashSet(tagNames);

boolean isContainingExistingTags = tagNamesSet.retainAll(tagPool);

if (isContainingExistingTags) {
    errorBag.put(parameterName, ERROR_TAGS_EXIST + YOU_SUPPLIED
            + StringUtil.convertIterableToString(tagNamesSet));
}
```
is sufficient

2016-10-31 13:35 UTC, li-kai commented on src/main/java/seedu/todo/model/tag/UniqueTagCollectionValidator.java
> +    private void validateTagNamesExist(Collection<Tag> tagPool, String... tagNames) {
```
Set<String> tagNamesSet = Sets.newHashSet(tagNames);

tagNamesSet.removeAll(tagPool);
if (!tagNamesSet.isEmpty()) {
    errorBag.put(parameterName, ERROR_TAGS_DO_NOT_EXIST + YOU_SUPPLIED
            + StringUtil.convertIterableToString(tagNamesSet));
}
```

then in `StringUtil`, use
```
public static String convertIterableToString( Iterable<?> iterable) {
    if (iterable == null) {
        return "";
    }
    return StringUtils.join(iterable, ", ");
}
```

2016-10-31 16:00 UTC, xiendong commented on src/main/java/seedu/todo/logic/commands/TagCommand.java
> +            = "An existing tag name, and a new tag name is required.";
Done

2016-10-31 16:00 UTC, xdrawks commented on src/main/java/seedu/todo/model/tag/UniqueTagCollectionValidator.java
> +    private void validateTagNamesExist(Collection<Tag> tagPool, String... tagNames) {
Done

2016-10-31 16:01 UTC, xdrawks commented on src/main/java/seedu/todo/model/tag/UniqueTagCollectionValidator.java
> +    private void validateTagNamesDoNotExist(Collection<Tag> tagPool, String... tagNames) {
Done

2016-10-31 16:01 UTC, xdrawks commented
Don't merge yet!

2016-11-01 11:03 UTC, li-kai approved these changes

2016-11-01 11:03 UTC, merged