Multiple indexed commands 2
CS2103AUG2016-W10-C4/main pull request #159
Opened 2016-10-30 16:00 UTC by cricketer94

Fixes #122. Can be extended to fix #110 as well.

2016-10-31 14:07 UTC, li-kai requested changes
Just some stylistic stuff. Otherwise looks pretty straightforward.

2016-10-31 14:07 UTC, li-kai commented on src/main/java/seedu/todo/logic/commands/TagCommand.java
> +            ImmutableTask task = model.getObservableList().get(displayedIndex - INDEX_OFFSET);
Use `model.getTask(displayedIndex)`

2016-10-31 14:07 UTC, li-kai commented on src/main/java/seedu/todo/model/TodoList.java
> +        for (Integer i : indexes) {
`for (Integer index : indexes)`, no need to rename the param 😄

2016-10-31 14:07 UTC, li-kai commented on src/main/java/seedu/todo/model/TodoList.java
> +        List<Integer> indexes = new ArrayList<>();
Use the array instantiation shorthand here. And explain why `get(0)` was used.

2016-10-31 14:07 UTC, li-kai commented on src/main/java/seedu/todo/model/TodoList.java
>          for (Integer i : indexes) {
Same problem, just rename the param in the for loop.

Explain why you're doing a for loop a second time (preventing partial updates)

2016-10-31 14:07 UTC, li-kai commented on src/main/java/seedu/todo/model/TodoModel.java
> +        for (int i = 1 ; i <= getObservableList().size() ; i++) {
[No spaces before semicolons](https://oss-generic.github.io/process/codingstandards/coding-standards-java.html#loops)

2016-10-31 14:07 UTC, li-kai commented on src/test/java/seedu/todo/logic/commands/ClearCommandTest.java
> +                                    } );
Mind your spaces `} )`. There's another one below, with wrong indentation too.

2016-10-31 14:07 UTC, li-kai commented on src/main/java/seedu/todo/model/TodoModel.java
> +            uniqueTagCollection.notifyTaskDeleted(taskToDelete);
What happens if a validation error occurs? Not all tasks are deleted now... 😆 
Only inform tags after all tasks are deleted.
Do it what you previously did (second for loop).

2016-10-31 15:15 UTC, cricketer94 commented on src/main/java/seedu/todo/logic/commands/TagCommand.java
> +            ImmutableTask task = model.getObservableList().get(displayedIndex - INDEX_OFFSET);
Whose branch is this on ah? Can't find leh

2016-10-31 15:16 UTC, cricketer94 commented on src/main/java/seedu/todo/model/TodoList.java
> +        for (Integer i : indexes) {
The use of i is generally the convention used when iterating through integers though :x

2016-10-31 15:37 UTC, li-kai commented on src/main/java/seedu/todo/logic/commands/TagCommand.java
> +            ImmutableTask task = model.getObservableList().get(displayedIndex - INDEX_OFFSET);
Xien Dong's branch has it...you called this method

2016-10-31 15:38 UTC, li-kai commented on src/main/java/seedu/todo/model/TodoList.java
> +        for (Integer i : indexes) {
Yes it's semantic in a for(int i = 0)... kind of loop, but not this.

2016-10-31 16:05 UTC, cricketer94 commented on src/main/java/seedu/todo/logic/commands/TagCommand.java
> +            ImmutableTask task = model.getObservableList().get(displayedIndex - INDEX_OFFSET);
Wrong model? Might only exist on the underlying layer. This model refers to the visible layer.

2016-10-31 17:34 UTC, ZhangYiJiang commented on src/main/java/seedu/todo/logic/commands/ClearCommand.java
> +        model.deleteAll();
Uh... I thought the `clear` command is a solution to #122 - specifically this was _not_ meant to be a delete all command, but rather all _completed_ tasks

2016-10-31 17:37 UTC, ZhangYiJiang commented on src/test/java/seedu/todo/logic/commands/ClearCommandTest.java
> +                                    } );
This is not the correct way to indent lambdas. Treat the `{ }` like any other braces - 

``` java
model.add("Hello", task -> {
    /// ... 
});
```

2016-11-01 04:58 UTC, cricketer94 commented on src/main/java/seedu/todo/logic/commands/ClearCommand.java
> +        model.deleteAll();
So do i prevent execution if the current view contains tasks which are not completed?

2016-11-01 07:38 UTC, li-kai commented on src/main/java/seedu/todo/logic/commands/TagCommand.java
> +            ImmutableTask task = model.getObservableList().get(displayedIndex - INDEX_OFFSET);
In that case, yeah, might be the wrong model 😅

2016-11-01 18:08 UTC, li-kai approved these changes

2016-11-02 00:22 UTC, merged